In [5]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score

data = {
    'Gender': ['male', 'male', 'male', 'male', 'female', 'female', 'female', 'female'],
    'Height': [6.00, 5.92, 5.58, 5.92, 5.00, 5.50, 5.42, 5.75],
    'Weight': [180, 190, 170, 165, 100, 150, 130, 150],
    'Foot_Size': [12, 11, 12, 10, 6, 8, 7, 9]
}

df = pd.DataFrame(data)
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])
X = df[['Height', 'Weight', 'Foot_Size']]
y = df['Gender']
clf = DecisionTreeClassifier()
clf.fit(X, y)

height = float(input("Enter Height: "))
weight = float(input("Enter Weight: "))
foot_size = float(input("Enter Foot Size: "))
new_entry = {'Height': height, 'Weight': weight, 'Foot_Size': foot_size}
new_entry_df = pd.DataFrame([new_entry])
predicted_gender = clf.predict(new_entry_df)[0]
predicted_gender_label = label_encoder.inverse_transform([predicted_gender])[0]
print(f"Predicted gender for the new entry: {predicted_gender_label}")

new_entry_df['Gender'] = predicted_gender
df = pd.concat([df, new_entry_df], ignore_index=True)

X = df[['Height', 'Weight', 'Foot_Size']]
y = df['Gender']
clf.fit(X, y)

print("\nNew entry added to the dataset and model retrained.")
print(df)

y_pred = clf.predict(X)
conf_matrix = confusion_matrix(y, y_pred)
accuracy = accuracy_score(y, y_pred)
print("Confusion Matrix:\n", conf_matrix)
print("Accuracy Score:", accuracy)

Enter Height:  5
Enter Weight:  43
Enter Foot Size:  160


Predicted gender for the new entry: male

New entry added to the dataset and model retrained.
   Gender  Height  Weight  Foot_Size
0       1    6.00   180.0       12.0
1       1    5.92   190.0       11.0
2       1    5.58   170.0       12.0
3       1    5.92   165.0       10.0
4       0    5.00   100.0        6.0
5       0    5.50   150.0        8.0
6       0    5.42   130.0        7.0
7       0    5.75   150.0        9.0
8       1    5.00    43.0      160.0
Confusion Matrix:
 [[4 0]
 [0 5]]
Accuracy Score: 1.0


In [6]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
# Step 1: Create the initial dataset
data = {
    'Gender': ['male', 'male', 'male', 'male', 'female', 'female', 'female', 'female'],
    'Height': [6.00, 5.92, 5.58, 5.92, 5.00, 5.50, 5.42, 5.75],
    'Weight': [180, 190, 170, 165, 100, 150, 130, 150],
    'Foot_Size': [12, 11, 12, 10, 6, 8, 7, 9]
}
df = pd.DataFrame(data)
# Step 2: Encode the 'Gender' column
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])
# Step 3: Separate features and target variable
X = df[['Height', 'Weight', 'Foot_Size']]
y = df['Gender']
# Step 4: Train the Decision Tree Classifier
clf = DecisionTreeClassifier()
clf.fit(X, y)
# Step 5: Get new entry from the user
height = float(input("Enter Height: "))
weight = float(input("Enter Weight: "))
foot_size = float(input("Enter Foot Size: "))
new_entry = {'Height': height, 'Weight': weight, 'Foot_Size': foot_size}
# Step 6: Predict the gender of the new entry
new_entry_df = pd.DataFrame([new_entry])
predicted_gender = clf.predict(new_entry_df)[0]
predicted_gender_label = label_encoder.inverse_transform([predicted_gender])[0]
print(f"Predicted gender for the new entry: {predicted_gender_label}")
# Step 7: Add the new entry with the predicted gender to the dataset
new_entry_df['Gender'] = predicted_gender
df = pd.concat([df, new_entry_df], ignore_index=True)
# Step 8: Retrain the classifier with the updated dataset
X = df[['Height', 'Weight', 'Foot_Size']]
y = df['Gender']
clf.fit(X, y)
# Step 9: Display the updated dataset
print("\nNew entry added to the dataset and model retrained.")
print(df)
# Step 10: Evaluate the model
y_pred = clf.predict(X)
conf_matrix = confusion_matrix(y, y_pred)
accuracy = accuracy_score(y, y_pred)
print("Confusion Matrix:\n", conf_matrix)
print("Accuracy Score:", accuracy)

Enter Height:  5.2
Enter Weight:  48
Enter Foot Size:  165


Predicted gender for the new entry: male

New entry added to the dataset and model retrained.
   Gender  Height  Weight  Foot_Size
0       1    6.00   180.0       12.0
1       1    5.92   190.0       11.0
2       1    5.58   170.0       12.0
3       1    5.92   165.0       10.0
4       0    5.00   100.0        6.0
5       0    5.50   150.0        8.0
6       0    5.42   130.0        7.0
7       0    5.75   150.0        9.0
8       1    5.20    48.0      165.0
Confusion Matrix:
 [[4 0]
 [0 5]]
Accuracy Score: 1.0


In [7]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
data = np.array([
    ['male', 6.00, 180, 12],
    ['male', 5.92, 190, 11],
    ['male', 5.58, 170, 12],
    ['male', 5.92, 165, 10],
    ['female', 5.00, 100, 6],
    ['female', 5.50, 150, 8],
    ['female', 5.42, 130, 7],
    ['female', 5.75, 150, 9]
])
X = data[:, 1:].astype(float)
y = data[:, 0]
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
clf = DecisionTreeClassifier()
clf.fit(X, y_encoded)
height = float(input("Enter Height: "))
weight = float(input("Enter Weight: "))
foot_size = float(input("Enter Foot Size: "))
new_entry = np.array([[height, weight, foot_size]])
predicted_gender = clf.predict(new_entry)[0]
predicted_gender_label = label_encoder.inverse_transform([predicted_gender])[0]
print(f"Predicted gender for the new entry: {predicted_gender_label}")
new_entry_with_gender = np.array([[predicted_gender_label, height, weight, foot_size]])
data = np.vstack([data, new_entry_with_gender])
X = data[:, 1:].astype(float)
y = data[:, 0]
y_encoded = label_encoder.fit_transform(y)
clf.fit(X, y_encoded)
print("\nNew entry added to the dataset and model retrained.")
print(data)
y_pred = clf.predict(X)
conf_matrix = confusion_matrix(y_encoded, y_pred)
accuracy = accuracy_score(y_encoded, y_pred)
print("Confusion Matrix:\n", conf_matrix)
print("Accuracy Score:", accuracy)

Enter Height:  23
Enter Weight:  322
Enter Foot Size:  123


Predicted gender for the new entry: male

New entry added to the dataset and model retrained.
[['male' '6.0' '180' '12']
 ['male' '5.92' '190' '11']
 ['male' '5.58' '170' '12']
 ['male' '5.92' '165' '10']
 ['female' '5.0' '100' '6']
 ['female' '5.5' '150' '8']
 ['female' '5.42' '130' '7']
 ['female' '5.75' '150' '9']
 ['male' '23.0' '322.0' '123.0']]
Confusion Matrix:
 [[4 0]
 [0 5]]
Accuracy Score: 1.0


In [8]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

data = {
    'Name of Country': ['China', 'US', 'India', 'Japan', 'Germany', 'Brazil', 'Indonesia', 'Russia', 'UK', 'France'],
    'Country_wise_plastic_waste': [59.05, 42.02, 26.33, 7.99, 6.28, 5.96, 5.85, 5.84, 5.03, 4.98],
    'Main_source': ['Packaging_Industrial', 'Packaging_consumer', 'Consumer_goods', 'Packaging_Electronics', 
                    'Automotive_Packaging', 'Consumer_Packaging', 'Food_Packaging', 'Industrial_Consumer', 
                    'Packaging_consumer', 'Packaging_consumer'],
    'Recycling_Rate': [29.8, 32.1, 11.5, 84.8, 56.1, 1.2, 11.8, 5.6, 46.2, 27.3],
    'Per_capital_waste': [41.2, 127.5, 19.3, 63.2, 75.6, 28.1, 21.3, 40.2, 74.3, 73.1],
    'Coastal_Waste': ['High', 'Medium', 'High', 'Medium', 'Low', 'Medium', 'Very_High', 'Medium', 'Low', 'Low']
}

# Encoding categorical data
le = LabelEncoder()
main_source_encoded = le.fit_transform(data['Main_source'])
coastal_waste_encoded = le.fit_transform(data['Coastal_Waste'])

# Preparing the feature set and target variable
X = np.array([
    data['Country_wise_plastic_waste'],
    main_source_encoded,
    data['Recycling_Rate'],
    data['Per_capital_waste']
]).T

y = coastal_waste_encoded

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scaling the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Using Decision Tree Classifier
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

# Making predictions
y_pred = clf.predict(X_test)

# Evaluating the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)

# Inverse transforming the predicted labels
y_pred_labels = le.inverse_transform(y_pred)
print("Predicted Coastal Waste Categories:", y_pred_labels)

Accuracy: 0.5
Confusion Matrix:
 [[0 0 0]
 [0 1 0]
 [1 0 0]]
Predicted Coastal Waste Categories: ['Low' 'High']
